import type { Persona } from '../types';

/**
 * In-app nudge audio.
 *
 * The OS plays the persona's notification sound when a nudge is delivered to a
 * backgrounded app — but when the app is already open, the system banner (and
 * its sound) is suppressed and the in-app persona card is all the user gets.
 * Without this, a nudge arriving while you're looking at the app is silent.
 *
 * Files live in public/sounds and are generated by scripts/gen-sounds.mjs, so
 * the same motif plays whether the nudge arrived through the OS or in-app.
 */

const cache = new Map<string, HTMLAudioElement>();

/** Warms the cache so the first nudge isn't delayed by a disk read. */
export function preloadPersonaSound(persona: Persona): void {
  void getAudio(persona.sound);
}

function getAudio(name: string): HTMLAudioElement | null {
  if (typeof Audio === 'undefined') return null;

  const existing = cache.get(name);
  if (existing) return existing;

  try {
    const audio = new Audio(`/sounds/${name}.wav`);
    audio.preload = 'auto';
    cache.set(name, audio);
    return audio;
  } catch {
    return null;
  }
}

/**
 * Plays the persona's sound. Never throws and never blocks the caller: a nudge
 * card must still appear even if audio is unavailable (autoplay policy, a
 * missing file, a device in silent mode).
 */
export function playPersonaSound(persona: Persona, enabled: boolean): void {
  if (!enabled) return;

  const audio = getAudio(persona.sound);
  if (!audio) return;

  try {
    // Rewind so rapid consecutive nudges each sound, rather than the second
    // being swallowed because the element is mid-playback.
    audio.currentTime = 0;
    const played = audio.play();
    // Browsers reject this promise when autoplay is blocked; that is expected
    // on the web preview before the user has interacted with the page.
    if (played && typeof played.catch === 'function') {
      played.catch(() => {});
    }
  } catch {
    // Audio is a nice-to-have, never a reason to break the alert.
  }
}
